### ISSUE TITLE
Help with submitting sbatch file that calls spaCy Python

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/digital-history#45]
Hi, Rob.

An undergraduate RA would like to submit an sbatch job for Python code that uses spaCy.

Can you please tell us how we can do that / what we need to add to your sbatch file? 

We seem to only be able to access spaCy interactively in that container you set up (source /hpc/applications/python_environments/spacy/bin/activate)

Thanks so much for your help.

**Comment by rkalescky** [comment]
I've added an example sbatch script in "text_mining_with_python" with dd9411bd452bd35269de8af444df3f40a30ffdba.
