### ISSUE TITLE
Issue with loading the parquet version of the Hansard data 

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/digital-history#47]
Oddly, some students are unable to load the parquet version of the Hansard data. 

When using:

```
import pandas as pd

hansard = pd.read_parquet("/scratch/group/oit_research_data/hansard/hansard_20191119.parquet")

hansard.head(5)
```
They get the error: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'. 

I confirmed these students are in the correct environment and used the correct directory paths.

**Comment by rkalescky** [comment]
The most likely situation is that students are not correctly pulling, or not doing so at all, the latest changes from the repo. I encountered this issue numerous times with students I helped during the previous class.

We can leave this issue open for a while until the few students noted in Slack have ok'd their situations.
