### ISSUE TITLE
Potential Issue with Prof. Guldi's M2 Account 

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/digital-history#48]
Hi, Rob.

Jo's M2 account has issues that limit her ability to use M2. As you might remember, despite that Jo had the correct file path for commands like `cp`, this command didn't work. 

Even after doing research, I cannot fathom what this might mean other than that she has some lower-level, corrupted files that might be limiting her ability to use M2. 

What do you advise? Should she obtain a new account with a fresh partition?

Thanks so much for your advice on this bizarre problem. 

Steph

**Comment by rkalescky** [comment]
The best next step is observe this behavior with Dr. Guldi. I asked the M2 admins to look again at this issue and they found nothing obviously wrong, but clearly something is amiss. @joguldi can schedule a time with me to investigate this issue.
