### ISSUE TITLE
"Counter()" is not defined in week7(1) notebook.

### ISSUE THREAD

**Issue by rkalescky** [stephbuon/digital-history#49]
I'm not sure if this notebook is needed as it appears to be modified copy, i.e. "(1)".

**Comment by stephbuon** [comment]
Thanks, Rob. 

I don't see Counter() in week7. The only Notebook I see with a (1) is: **hist3368-week3-controlled-vocab(1).ipynb**, which also invokes Counter(). 

Am I looking at the same thing you are?

**Comment by rkalescky** [comment]
That's correct; only the "(1)" notebook calls this function.

**Comment by stephbuon** [comment]
I appreciate it, @rkalescky -- just wanted to make sure we weren't looking at separate things, and I go down a rabbit hole trying to fix the wrong thing!!
