### ISSUE TITLE
Fix matching issue 

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/digital-history#7]
In  **digital-history/expert-vocab/hist3368-week3-controlled-vocab.ipynb** , figure out why we are not matching with more words and fix issue: 

`controlled_words = []

for w in words:
    if w.lower() in controlled_vocab:
        controlled_words.append(w)

Counter(controlled_words) # counter is not working properly here `

**Comment by alexanderr** [comment]
Fixed in 95fb4a3f1d4934f1177d931a42f9ac5427ce88a7
