### ISSUE TITLE
Print lemmas

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/digital-history#8]
In  **digital-history/expert-vocab/hist3368-week3-controlled-vocab.ipynb**, under section "Counting N-grams", change the code so we print a truncated list of lemmas: 

`from nltk.stem import WordNetLemmatizer
from textblob import TextBlob

lemmatizer = WordNetLemmatizer()
three_grams_list = []

for lemma in lemma_list:
    if lemma is not None: # remove once alexander removes None values
    #print(TextBlob(d).ngrams(n=3))
        three_grams = TextBlob(lemma).ngrams(n=3)
        three_grams_list.append(three_grams)

three_grams_list[:20]`

**Comment by alexanderr** [comment]
Fixed in 95fb4a3f1d4934f1177d931a42f9ac5427ce88a7
