### ISSUE TITLE
Remove 'None' values

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/digital-history#9]
In  **digital-history/expert-vocab/hist3368-week3-controlled-vocab.ipynb**  remove 'None' values from lemma_list. See the output of: 

`lemma_list = []

for d in data:
    for w in words:
        w = w.lower().strip('",.;:?([)]_') 
        lemma = wn.morphy(w)
        lemma_list.append(lemma)

lemma_list[:20]`

**Comment by alexanderr** [comment]
Fixed in 95fb4a3f1d4934f1177d931a42f9ac5427ce88a7
